import { useMemo, useState } from "react";
import { CheckCircle2, CircleAlert, Download, Printer, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { estruturaBalanceteNitaplast, type LinhaEstruturaBalancete } from "@/data/nitaplast-balancete-estrutura";
import { saldoAberturaJulhoPorConta } from "@/data/nitaplast-saldos-julho";
import {
  lancamentosIntegradosJulhoFinal,
  pendenciasJulhoFinal,
  resumoFechamentoJulhoFinal,
  totalCreditosJulhoFinal,
  totalDebitosJulhoFinal,
} from "@/data/nitaplast-razao-julho-final";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const arred=(v:number)=>Math.round(v*100)/100;

type LinhaBalancete = LinhaEstruturaBalancete & {saldoAnterior:number;debitos:number;creditos:number;movimento:number;saldoAtual:number;lancamentos:number};
function descendente(a:LinhaEstruturaBalancete,s:LinhaEstruturaBalancete){return a.classificacao===s.classificacao||a.classificacao.startsWith(`${s.classificacao}.`);}
function calcularBalancete():LinhaBalancete[]{
  const mov=new Map<string,{debitos:number;creditos:number;lancamentos:number}>();
  for(const x of lancamentosIntegradosJulhoFinal){
    const d=mov.get(x.debitoCodigo)??{debitos:0,creditos:0,lancamentos:0};d.debitos+=x.valor;d.lancamentos++;mov.set(x.debitoCodigo,d);
    const c=mov.get(x.creditoCodigo)??{debitos:0,creditos:0,lancamentos:0};c.creditos+=x.valor;c.lancamentos++;mov.set(x.creditoCodigo,c);
  }
  const analiticas=estruturaBalanceteNitaplast.filter(x=>x.tipo==="A");
  const vals=new Map<string,{saldoAnterior:number;debitos:number;creditos:number;movimento:number;saldoAtual:number;lancamentos:number}>();
  for(const x of analiticas){const m=mov.get(x.conta)??{debitos:0,creditos:0,lancamentos:0};const sa=saldoAberturaJulhoPorConta.get(x.conta)??0;const liq=arred(m.debitos-m.creditos);vals.set(x.conta,{saldoAnterior:sa,debitos:arred(m.debitos),creditos:arred(m.creditos),movimento:liq,saldoAtual:arred(sa+liq),lancamentos:m.lancamentos});}
  return estruturaBalanceteNitaplast.map(x=>{
    if(x.tipo==="A")return {...x,...(vals.get(x.conta)??{saldoAnterior:0,debitos:0,creditos:0,movimento:0,saldoAtual:0,lancamentos:0})};
    const t={saldoAnterior:0,debitos:0,creditos:0,movimento:0,saldoAtual:0,lancamentos:0};
    for(const a of analiticas){if(!descendente(a,x))continue;const v=vals.get(a.conta);if(!v)continue;t.saldoAnterior+=v.saldoAnterior;t.debitos+=v.debitos;t.creditos+=v.creditos;t.movimento+=v.movimento;t.saldoAtual+=v.saldoAtual;t.lancamentos+=v.lancamentos;}
    return {...x,saldoAnterior:arred(t.saldoAnterior),debitos:arred(t.debitos),creditos:arred(t.creditos),movimento:arred(t.movimento),saldoAtual:arred(t.saldoAtual),lancamentos:t.lancamentos};
  });
}
const balancete=calcularBalancete();

function Header({titulo,descricao,acoes}:{titulo:string;descricao:string;acoes?:React.ReactNode}){return <div className="flex flex-wrap items-start justify-between gap-3 border-b pb-4"><div><h1 className="text-xl font-semibold tracking-tight">{titulo}</h1><p className="mt-1 text-sm text-muted-foreground">{descricao}</p></div><div className="flex flex-wrap gap-2">{acoes}<Badge variant="outline" className="border-amber-400 text-amber-800">Consolidado · 07/2026 · Em fechamento</Badge></div></div>}
function Metric({label,value,money=true}:{label:string;value:number;money?:boolean}){return <Card><CardContent className="pt-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums">{money?brl.format(value):value.toLocaleString("pt-BR")}</p></CardContent></Card>}
function Money({value,strong=false}:{value:number;strong?:boolean}){return <td className={`p-2 text-right tabular-nums ${strong?"font-semibold":""}`}>{value<0?`(${brl.format(Math.abs(value))})`:brl.format(value)}</td>}
function exportar(nome:string,linhas:string[][],sep=";"){const texto=linhas.map(r=>r.map(v=>String(v).replaceAll('"','""')).map(v=>`"${v}"`).join(sep)).join("\n");const blob=new Blob(["\ufeff",texto],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=nome;a.click();URL.revokeObjectURL(a.href);}

export function BalanceteJulho(){
  const [busca,setBusca]=useState("");const [grupo,setGrupo]=useState("todos");const [soMov,setSoMov]=useState(false);const [zeradas,setZeradas]=useState(false);
  const linhas=useMemo(()=>balancete.filter(x=>{const q=busca.trim().toLocaleLowerCase("pt-BR");const zero=Math.abs(x.saldoAnterior)<.005&&Math.abs(x.debitos)<.005&&Math.abs(x.creditos)<.005&&Math.abs(x.saldoAtual)<.005;if(!zeradas&&zero)return false;if(soMov&&Math.abs(x.debitos)+Math.abs(x.creditos)<.005)return false;if(grupo!=="todos"&&x.grupo!==grupo)return false;if(q&&![x.conta,x.classificacao,x.descricao].join(" ").toLocaleLowerCase("pt-BR").includes(q))return false;return true;}),[busca,grupo,soMov,zeradas]);
  const ativo=Math.abs(balancete.find(x=>x.classificacao==="1")?.saldoAnterior??0);const passivo=Math.abs(balancete.find(x=>x.classificacao==="2")?.saldoAnterior??0);
  const csv=()=>exportar("Balancete_Nitaplast_07-2026.csv",[["Conta","S/A","Classificação","Descrição","Saldo anterior","Débito","Crédito","Movimento","Saldo atual"],...linhas.map(x=>[x.conta,x.tipo,x.classificacao,x.descricao,String(x.saldoAnterior),String(x.debitos),String(x.creditos),String(x.movimento),String(x.saldoAtual)])]);
  return <div className="grid gap-5">
    <Header titulo="Balancete consolidado - Nitaplast" descricao="Saldos anteriores em 30/06/2026 e movimentação contábil da competência 07/2026." acoes={<><Button variant="outline" size="sm" onClick={csv}><Download className="mr-2 size-4"/>Exportar CSV</Button><Button variant="outline" size="sm" onClick={csv}><Download className="mr-2 size-4"/>Exportar Excel</Button><Button variant="outline" size="sm" onClick={()=>window.print()}><Printer className="mr-2 size-4"/>Imprimir / PDF</Button></>}/>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Ativo consolidado em 30/06" value={ativo}/><Metric label="Passivo + PL consolidado em 30/06" value={passivo}/><Metric label="Linhas do balancete" value={linhas.length} money={false}/><Metric label="Débitos consolidados 07" value={totalDebitosJulhoFinal}/><Metric label="Créditos consolidados 07" value={totalCreditosJulhoFinal}/><Metric label="Lançamentos em revisão" value={pendenciasJulhoFinal.length} money={false}/></div>
    <Card className="border-emerald-500/40 bg-emerald-50/40"><CardContent className="pt-6"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 size-5 text-emerald-700"/><div><p className="font-semibold">Balancete consolidado e recalculável</p><p className="mt-1 text-sm text-muted-foreground">Matriz e filial são apresentadas no mesmo balancete. O saldo de 30/06 é apenas referência de cálculo; os movimentos de 07/2026 nascem do Razão. Débitos e créditos permanecem equilibrados em {brl.format(totalDebitosJulhoFinal)}.</p></div></div></CardContent></Card>
    <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="text-base">Balancete consolidado - Débito, Crédito e Movimento</CardTitle><p className="mt-1 text-xs text-muted-foreground">NITAPLAST IND E COM DE PLÁSTICOS INDUSTRIAIS LTDA · 01/07/2026 a 31/07/2026</p></div><div className="relative w-full sm:w-96"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar conta, classificação ou descrição"/></div></div></CardHeader><CardContent>
      <div className="mb-4 flex flex-wrap gap-2"><Button size="sm" variant={grupo==="todos"?"default":"outline"} onClick={()=>setGrupo("todos")}>Todos</Button><Button size="sm" variant={grupo==="Ativo"?"default":"outline"} onClick={()=>setGrupo("Ativo")}>Ativo</Button><Button size="sm" variant={grupo==="Passivo e patrimônio líquido"?"default":"outline"} onClick={()=>setGrupo("Passivo e patrimônio líquido")}>Passivo e PL</Button><Button size="sm" variant={grupo==="Receitas acumuladas"?"default":"outline"} onClick={()=>setGrupo("Receitas acumuladas")}>Receitas</Button><Button size="sm" variant={grupo==="Custos e despesas acumulados"?"default":"outline"} onClick={()=>setGrupo("Custos e despesas acumulados")}>Custos e despesas</Button><Button size="sm" variant={soMov?"default":"outline"} onClick={()=>setSoMov(v=>!v)}>Somente com movimento</Button><Button size="sm" variant={zeradas?"default":"outline"} onClick={()=>setZeradas(v=>!v)}>Exibir contas zeradas</Button></div>
      <p className="mb-3 text-xs text-muted-foreground">{linhas.length} linhas exibidas. Contas sem saldo anterior, sem movimentação e com saldo atual zero ficam ocultas por padrão.</p>
      <div className="overflow-x-auto"><table className="w-full min-w-[1350px] text-sm"><thead><tr className="border-b bg-muted text-left text-xs"><th className="p-2">Conta contábil</th><th className="p-2">S/A</th><th className="p-2">Classificação</th><th className="p-2">Descrição</th><th className="p-2 text-right">Saldo anterior</th><th className="p-2 text-right">Débito</th><th className="p-2 text-right">Crédito</th><th className="p-2 text-right">Movimento</th><th className="p-2 text-right">Saldo atual</th><th className="p-2 text-right">Detalhe</th></tr></thead><tbody>{linhas.map(x=><tr key={`${x.tipo}-${x.conta}-${x.classificacao}`} className={`border-b ${x.tipo==="S"?(x.nivel<=2?"bg-blue-100/70":"bg-emerald-50/60")+" font-semibold":""}`}><td className="p-2 font-mono">{x.conta}</td><td className="p-2">{x.tipo}</td><td className="p-2 font-mono text-xs">{x.classificacao}</td><td className="p-2" style={{paddingLeft:8+Math.max(0,x.nivel-1)*10}}>{x.descricao}</td><Money value={x.saldoAnterior}/><Money value={x.debitos}/><Money value={x.creditos}/><Money value={x.movimento}/><Money value={x.saldoAtual} strong/><td className="p-2 text-right">{x.tipo==="A"?<Button size="sm" variant="outline" onClick={()=>window.location.assign(`/contabil/razao?conta=${encodeURIComponent(x.conta)}`)}>Abrir Razão</Button>:"—"}</td></tr>)}</tbody></table></div>
    </CardContent></Card>
    <PendenciaFonte/>
  </div>;
}

function filtroLancamentos(busca:string,conta:string){const q=busca.trim().toLocaleLowerCase("pt-BR");return lancamentosIntegradosJulhoFinal.filter(x=>(!conta||x.debitoCodigo===conta||x.creditoCodigo===conta)&&(!q||[x.id,x.origem,x.historico,x.documento,x.debito,x.credito,x.cc,x.centroCusto,x.fonte].join(" ").toLocaleLowerCase("pt-BR").includes(q)));}

export function RazaoJulho(){const contaUrl=typeof window==="undefined"?"":new URLSearchParams(window.location.search).get("conta")??"";const[conta,setConta]=useState(contaUrl);const[busca,setBusca]=useState("");const linhas=useMemo(()=>filtroLancamentos(busca,conta),[busca,conta]);const abertura=conta?(saldoAberturaJulhoPorConta.get(conta)??0):0;const mov=conta?linhas.reduce((s,x)=>s+(x.debitoCodigo===conta?x.valor:0)-(x.creditoCodigo===conta?x.valor:0),0):0;return <div className="grid gap-5"><Header titulo="Razão contábil - Nitaplast 07/2026" descricao="Movimentação contábil da competência 07/2026, formada pelos documentos fiscais, bancos, aplicações, impostos, fechamento de estoque e depreciação do imobilizado."/><div className="grid gap-3 sm:grid-cols-3"><Metric label="Partidas exibidas" value={linhas.length} money={false}/><Metric label="Saldo anterior da conta" value={abertura}/><Metric label="Saldo atual da conta" value={arred(abertura+mov)}/></div><Card><CardHeader><div className="flex flex-wrap gap-2"><Input className="w-full sm:w-48" value={conta} onChange={e=>setConta(e.target.value)} placeholder="Filtrar conta"/><div className="relative w-full sm:flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar histórico, documento, origem, CC..."/></div></div></CardHeader><CardContent className="overflow-x-auto"><TabelaLancamentos linhas={linhas}/></CardContent></Card><PendenciaFonte/></div>}

export function DiarioJulho(){const[busca,setBusca]=useState("");const linhas=useMemo(()=>[...filtroLancamentos(busca,"")].sort((a,b)=>a.data.localeCompare(b.data)||a.id.localeCompare(b.id)),[busca]);return <div className="grid gap-5"><Header titulo="Diário contábil - Nitaplast 07/2026" descricao="Livro Diário da competência 07/2026. Cada partida mantém débito, crédito, documento, histórico, centro de custo e fonte."/><div className="grid gap-3 sm:grid-cols-3"><Metric label="Partidas" value={linhas.length} money={false}/><Metric label="Total Débitos" value={totalDebitosJulhoFinal}/><Metric label="Total Créditos" value={totalCreditosJulhoFinal}/></div><Card><CardHeader><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar no Diário"/></div></CardHeader><CardContent className="overflow-x-auto"><TabelaLancamentos linhas={linhas}/></CardContent></Card><PendenciaFonte/></div>}

export function LancamentosJulho(){const[busca,setBusca]=useState("");const linhas=useMemo(()=>filtroLancamentos(busca,""),[busca]);const csv=()=>exportar("Lancamentos_Nitaplast_07-2026.csv",[["ID","Data","Origem","Débito","Crédito","Histórico","Documento","CC","Centro de Custo","Valor","Status","Fonte"],...linhas.map(x=>[x.id,x.data,x.origem,x.debito,x.credito,x.historico,x.documento,x.cc,x.centroCusto,String(x.valor),x.status,x.fonte])]);return <div className="grid gap-5"><Header titulo="Lançamentos contábeis - Nitaplast 07/2026" descricao="Partidas que formam o Razão, Balancete e DRE de julho. Nenhuma abertura gerencial é lançada no Razão." acoes={<Button variant="outline" size="sm" onClick={csv}><Download className="mr-2 size-4"/>Exportar CSV</Button>}/><div className="grid gap-3 sm:grid-cols-4"><Metric label="Lançamentos" value={lancamentosIntegradosJulhoFinal.length} money={false}/><Metric label="Débitos" value={totalDebitosJulhoFinal}/><Metric label="Créditos" value={totalCreditosJulhoFinal}/><Metric label="Em revisão" value={pendenciasJulhoFinal.length} money={false}/></div><Card><CardHeader><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar lançamento, conta, documento ou fonte"/></div></CardHeader><CardContent className="overflow-x-auto"><TabelaLancamentos linhas={linhas}/></CardContent></Card><PendenciaFonte/></div>}

function TabelaLancamentos({linhas}:{linhas:typeof lancamentosIntegradosJulhoFinal}){return <table className="w-full min-w-[1450px] text-xs"><thead><tr className="border-b bg-muted text-left"><th className="p-2">Data</th><th className="p-2">ID / Origem</th><th className="p-2">Débito</th><th className="p-2">Crédito</th><th className="p-2">Histórico / Documento</th><th className="p-2">CC</th><th className="p-2 text-right">Valor</th><th className="p-2">Status</th></tr></thead><tbody>{linhas.map(x=><tr key={x.id} className="border-b align-top"><td className="p-2 whitespace-nowrap">{x.data}</td><td className="p-2"><p className="font-mono font-medium">{x.id}</p><p className="text-[10px] text-muted-foreground">{x.origem}</p></td><td className="p-2"><p className="font-mono">{x.debitoCodigo}</p><p>{x.debito.replace(`${x.debitoCodigo} - `,"")}</p></td><td className="p-2"><p className="font-mono">{x.creditoCodigo}</p><p>{x.credito.replace(`${x.creditoCodigo} - `,"")}</p></td><td className="p-2 max-w-[420px]"><p>{x.historico}</p><p className="text-[10px] text-muted-foreground">{x.documento} · {x.fonte}</p></td><td className="p-2"><span className="font-mono">{x.cc}</span><br/>{x.centroCusto}</td><td className="p-2 text-right font-semibold tabular-nums">{brl.format(x.valor)}</td><td className="p-2">{x.status==="validado"?<span className="inline-flex items-center gap-1 text-emerald-700"><CheckCircle2 className="size-4"/>Validado</span>:<span className="inline-flex items-center gap-1 text-amber-700"><CircleAlert className="size-4"/>Revisar</span>}</td></tr>)}</tbody></table>}

function PendenciaFonte(){return <Card className="border-amber-400/50 bg-amber-50/40"><CardContent className="pt-5"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 size-5 text-amber-700"/><div><p className="font-semibold">Item sem fonte documental de julho localizada no pacote</p><p className="mt-1 text-sm text-muted-foreground">A escrituração já incorpora bancos, aplicações e rendimentos documentados, impostos a recuperar/recolher, PIS/COFINS, ICMS/IPI, compras, centro de custo, matriz/filial, fechamento de estoques e <strong>depreciação do imobilizado</strong>. Permanece sem lançamento somente <strong>Folha/provisões de 07/2026</strong>. A depreciação de julho usa a recorrência efetivamente contabilizada em 06/2026 limitada ao saldo residual, sem estimativa de taxa ou vida útil. JCP e variação cambial continuam fora por decisão operacional.</p><p className="mt-2 text-xs text-muted-foreground">Pendências analíticas existentes no próprio material continuam em revisão, sem conta genérica de encaixe. Valor bancário em revisão: {brl.format(resumoFechamentoJulhoFinal.pendenciasBancariasValor)}.</p></div></div></CardContent></Card>}