import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { Printer, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { estruturaBalanceteNitaplast } from "@/data/nitaplast-balancete-estrutura";
import { saldosImplantacao } from "@/data/nitaplast-implantacao";
import { saldoAberturaAgostoPorConta } from "@/data/nitaplast-saldos-agosto";
import { estabelecimentoLancamentoNitaplast } from "@/data/nitaplast-estabelecimento";
import { useLancamentosCompetencia } from "@/hooks/use-lancamentos-competencia";

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const arred=(v:number)=>Math.round(v*100)/100;
const info=new Map(saldosImplantacao.map(x=>[x.conta,x]));
const analiticas=estruturaBalanceteNitaplast.filter(x=>x.tipo==="A");
const contasEstrutura=new Set(analiticas.map(x=>x.conta));

function useBase(){return useLancamentosCompetencia("nitaplast-matriz","2026-08");}
function Header({titulo,descricao}:{titulo:string;descricao:string}){return <div className="flex flex-wrap items-start justify-between gap-3 border-b pb-4"><div><h1 className="text-xl font-semibold">{titulo}</h1><p className="mt-1 text-sm text-muted-foreground">{descricao}</p></div><Badge variant="outline">Matriz + Filial SP · 08/2026</Badge></div>}
function Metric({label,valor}:{label:string;valor:number}){return <Card><CardContent className="pt-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums">{brl.format(valor)}</p></CardContent></Card>}

function calcular(lancamentos:ReturnType<typeof useBase>["lancamentos"]){
  const mov=new Map<string,{d:number;c:number;n:number}>();
  for(const l of lancamentos){const d=mov.get(l.debitoCodigo)??{d:0,c:0,n:0};d.d+=l.valor;d.n++;mov.set(l.debitoCodigo,d);const c=mov.get(l.creditoCodigo)??{d:0,c:0,n:0};c.c+=l.valor;c.n++;mov.set(l.creditoCodigo,c);}
  const extras=[...mov.keys()].filter(c=>!contasEstrutura.has(c)).map(c=>({conta:c,tipo:"A" as const,classificacao:info.get(c)?.classificacao??"9.9.99",descricao:info.get(c)?.descricao??"Conta não encontrada no plano",nivel:9}));
  const estrutura=[...estruturaBalanceteNitaplast,...extras];
  const valores=new Map([...analiticas,...extras].map(a=>{const m=mov.get(a.conta)??{d:0,c:0,n:0};const sa=saldoAberturaAgostoPorConta.get(a.conta)??0;return[a.conta,{sa,d:arred(m.d),c:arred(m.c),mov:arred(m.d-m.c),sf:arred(sa+m.d-m.c),n:m.n}] as const;}));
  return estrutura.map(x=>{if(x.tipo==="A")return{...x,...valores.get(x.conta)!};const filhas=[...valores].filter(([conta])=>{const a=[...analiticas,...extras].find(y=>y.conta===conta);return a&&(a.classificacao===x.classificacao||a.classificacao.startsWith(`${x.classificacao}.`));}).map(([,v])=>v);return{...x,...filhas.reduce((t,v)=>({sa:t.sa+v.sa,d:t.d+v.d,c:t.c+v.c,mov:t.mov+v.mov,sf:t.sf+v.sf,n:t.n+v.n}),{sa:0,d:0,c:0,mov:0,sf:0,n:0})};});
}

export function BalanceteAgostoCompleto(){const{lancamentos}=useBase();const linhas=useMemo(()=>calcular(lancamentos),[lancamentos]);const[busca,setBusca]=useState("");const q=busca.toLowerCase();const vis=linhas.filter(x=>(Math.abs(x.sa)+Math.abs(x.d)+Math.abs(x.c)+Math.abs(x.sf)>.004)&&(!q||`${x.conta} ${x.classificacao} ${x.descricao}`.toLowerCase().includes(q)));const total=arred(lancamentos.reduce((s,x)=>s+x.valor,0));return <div className="grid gap-5"><Header titulo="Balancete consolidado - Nitaplast" descricao="Razão → Balancete → DRE. Saldos anteriores de 07/2026 e movimento contábil de 08/2026."/><div className="grid gap-3 sm:grid-cols-4"><Metric label="Débitos 08" valor={total}/><Metric label="Créditos 08" valor={total}/><Metric label="Diferença contábil" valor={0}/><Metric label="Saldo analítico assinado" valor={arred(linhas.filter(x=>x.tipo==="A").reduce((s,x)=>s+x.sf,0))}/></div><Card><CardHeader><div className="flex justify-between gap-3"><CardTitle>Balancete 08/2026 · {linhas.length} linhas</CardTitle><div className="flex gap-2"><Input value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar conta"/><Button variant="outline" onClick={()=>window.print()}><Printer className="mr-2 size-4"/>Imprimir</Button></div></div></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[1350px] text-sm"><thead><tr className="border-b bg-muted"><th className="p-2 text-left">Conta</th><th> S/A </th><th className="text-left">Classificação</th><th className="text-left">Descrição</th><th>Saldo anterior</th><th>Débito</th><th>Crédito</th><th>Movimento</th><th>Saldo atual</th><th>Detalhe</th></tr></thead><tbody>{vis.map(x=><tr key={`${x.tipo}-${x.conta}`} className={`border-b ${x.tipo==="S"?"bg-muted/30 font-semibold":""}`}><td className="p-2 font-mono">{x.conta}</td><td className="text-center">{x.tipo}</td><td className="font-mono">{x.classificacao}</td><td>{x.descricao}</td>{[x.sa,x.d,x.c,x.mov,x.sf].map((v,i)=><td key={i} className="p-2 text-right tabular-nums">{brl.format(arred(v))}</td>)}<td>{x.tipo==="A"?<Button asChild size="sm" variant="outline"><Link to="/contabil/razao" search={{conta:x.conta} as never}>Abrir Razão</Link></Button>:"—"}</td></tr>)}</tbody></table></CardContent></Card></div>}

function Tabela({linhas}:{linhas:ReturnType<typeof useBase>["lancamentos"]}){return <div className="overflow-x-auto"><table className="w-full min-w-[1600px] text-xs"><thead><tr className="border-b bg-muted text-left"><th>Data</th><th>Estabelecimento</th><th>ID/Origem</th><th>Débito</th><th>Crédito</th><th>Histórico/Documento</th><th>CC</th><th className="text-right">Valor</th><th>Status</th></tr></thead><tbody>{linhas.map(x=><tr key={x.id} className="border-b"><td className="p-2">{x.data}</td><td>{estabelecimentoLancamentoNitaplast(x as never)}</td><td><b className="font-mono">{x.id}</b><br/>{x.origem}</td><td>{x.debitoCodigo} - {info.get(x.debitoCodigo)?.descricao}</td><td>{x.creditoCodigo} - {info.get(x.creditoCodigo)?.descricao}</td><td>{x.historico}<br/><span className="text-muted-foreground">{x.documento}</span></td><td>{x.cc} - {x.centroCusto}</td><td className="text-right">{brl.format(x.valor)}</td><td>{x.status}</td></tr>)}</tbody></table></div>}
function Livro({tipo}:{tipo:"Razão"|"Diário"|"Lançamentos"}){const{lancamentos}=useBase();const[busca,setBusca]=useState("");const conta=tipo==="Razão"&&typeof window!=="undefined"?new URLSearchParams(location.search).get("conta")??"":"";const q=busca.toLowerCase();const linhas=lancamentos.filter(x=>(!conta||x.debitoCodigo===conta||x.creditoCodigo===conta)&&(!q||JSON.stringify(x).toLowerCase().includes(q))).sort((a,b)=>a.data.localeCompare(b.data));return <div className="grid gap-5"><Header titulo={`${tipo} contábil - Nitaplast 08/2026`} descricao="Mesma base contábil utilizada pelo Balancete e pela DRE detalhada."/><Card><CardHeader><div className="relative"><Search className="absolute left-3 top-2.5 size-4"/><Input className="pl-9" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar conta, documento, histórico ou centro de custo"/></div></CardHeader><CardContent><Tabela linhas={linhas}/></CardContent></Card></div>}
export const RazaoAgostoCompleto=()=> <Livro tipo="Razão"/>;export const DiarioAgostoCompleto=()=> <Livro tipo="Diário"/>;export const LancamentosAgostoCompleto=()=> <Livro tipo="Lançamentos"/>;

export function DreAgostoCompleta(){const{lancamentos}=useBase();const grupos=useMemo(()=>{const m=new Map<string,{descricao:string,valor:number,tipo:"R"|"D"}>();for(const l of lancamentos){for(const [conta,sinal] of [[l.creditoCodigo,1],[l.debitoCodigo,-1]] as const){const i=info.get(conta);if(i?.grupo==="Receitas acumuladas"){const a=m.get(conta)??{descricao:i.descricao,valor:0,tipo:"R"};a.valor+=sinal*l.valor;m.set(conta,a);}if(i?.grupo==="Custos e despesas acumulados"){const a=m.get(conta)??{descricao:i.descricao,valor:0,tipo:"D"};a.valor-=sinal*l.valor;m.set(conta,a);}}}return[...m].filter(([,x])=>Math.abs(x.valor)>.004);},[lancamentos]);const receitas=arred(grupos.filter(([,x])=>x.tipo==="R").reduce((s,[,x])=>s+x.valor,0));const despesas=arred(grupos.filter(([,x])=>x.tipo==="D").reduce((s,[,x])=>s+x.valor,0));return <div className="grid gap-5"><Header titulo="DRE detalhada - Nitaplast 08/2026" descricao="DRE derivada do movimento analítico do mesmo Razão que forma o Balancete."/><Card><CardContent className="pt-5"><table className="w-full text-sm"><tbody><tr className="border-b font-semibold"><td className="p-2">RECEITAS</td><td className="text-right">{brl.format(receitas)}</td></tr>{grupos.filter(([,x])=>x.tipo==="R").map(([c,x])=><tr key={c} className="border-b"><td className="p-2 pl-6">{c} - {x.descricao}</td><td className="text-right">{brl.format(x.valor)}</td></tr>)}<tr className="border-b font-semibold"><td className="p-2">CUSTOS E DESPESAS</td><td className="text-right">{brl.format(despesas)}</td></tr>{grupos.filter(([,x])=>x.tipo==="D").map(([c,x])=><tr key={c} className="border-b"><td className="p-2 pl-6">{c} - {x.descricao}</td><td className="text-right">{brl.format(x.valor)}</td></tr>)}<tr className="text-base font-bold"><td className="p-3">RESULTADO PARCIAL</td><td className="text-right">{brl.format(receitas-despesas)}</td></tr></tbody></table></CardContent></Card></div>}
