import { useMemo, useState } from "react";
import { CheckCircle2, ChevronDown, ChevronRight, CircleAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { composicaoResultadoJulhoFinal, dreJulhoFinal } from "@/data/nitaplast-dre-julho-final";
import { receitaFiscalJulho } from "@/data/nitaplast-fechamento-julho";
import { lancamentosIntegradosJulhoFinal, resumoFechamentoJulhoFinal } from "@/data/nitaplast-razao-julho-final";

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const arred=(v:number)=>Math.round(v*100)/100;
type Item=(typeof composicaoResultadoJulhoFinal)[number];
type Linha={id:string;descricao:string;nivel:number;valor:number;criterio:string;composicao?:Item[];status?:"calculado"|"pendente"};
const ccProd=new Set(["101","102","103","104","105","106","107","108","109","110","111","503","10014","10032","10058","19999"]);
const ccCom=new Set(["201","202","203","204","205","206","207","209","210","502"]);
const ccAdm=new Set(["301","302","303","304","305","306"]);
function soma(a:Item[]){return arred(a.reduce((s,x)=>s+x.valor,0));}
function mov(c:string){return arred(lancamentosIntegradosJulhoFinal.reduce((s,x)=>s+(x.debitoCodigo===c?x.valor:0)-(x.creditoCodigo===c?x.valor:0),0));}

export function DreJulhoCompleta(){
  const[abertas,setAbertas]=useState<Set<string>>(new Set(["receita","deducoes","custos","despesas"]));
  const grupos=useMemo(()=>{const custos=composicaoResultadoJulhoFinal.filter(x=>x.classificacao.startsWith("4.2")||x.classificacao.startsWith("5.1"));const financeira=composicaoResultadoJulhoFinal.filter(x=>x.classificacao.startsWith("5.8"));const despesas=composicaoResultadoJulhoFinal.filter(x=>x.classificacao.startsWith("5.")&&!x.classificacao.startsWith("5.1")&&!x.classificacao.startsWith("5.8"));const prod=despesas.filter(x=>ccProd.has(x.cc));const comerciais=despesas.filter(x=>ccCom.has(x.cc));const adm=despesas.filter(x=>ccAdm.has(x.cc));const outras=despesas.filter(x=>!ccProd.has(x.cc)&&!ccCom.has(x.cc)&&!ccAdm.has(x.cc));return{custos,financeira,despesas,prod,comerciais,adm,outras};},[]);
  const lucroBruto=arred(dreJulhoFinal.receitaLiquida-dreJulhoFinal.custosReconhecidos);
  const despOper=soma(grupos.despesas);const despFin=soma(grupos.financeira);const resultadoOper=arred(lucroBruto-despOper);
  const linhas:Linha[]=[
    {id:"receita",descricao:"(+) Receita Operacional Bruta",nivel:0,valor:dreJulhoFinal.receitaBruta,criterio:"Receita formada exclusivamente pelas saídas fiscais contabilizadas no Razão."},
    {id:"rmp",descricao:"Receita Venda Produção Matriz",nivel:1,valor:receitaFiscalJulho.matriz.producao,criterio:"Saídas fiscais externas da matriz."},
    {id:"rmr",descricao:"Receita Revenda Matriz",nivel:1,valor:receitaFiscalJulho.matriz.revenda,criterio:"Saídas fiscais de revenda da matriz."},
    {id:"rfp",descricao:"Receita Venda Produção Filial",nivel:1,valor:receitaFiscalJulho.filialSp.producaoOperacaoTriangular,criterio:"Operação triangular/produção da filial."},
    {id:"rfr",descricao:"Receita Revenda Filial",nivel:1,valor:receitaFiscalJulho.filialSp.revenda,criterio:"Saídas fiscais da filial."},
    {id:"deducoes",descricao:"(-) Deduções da Receita Bruta",nivel:0,valor:dreJulhoFinal.deducoes,criterio:"Movimento líquido das contas de devoluções e tributos incidentes nas vendas no Razão."},
    {id:"dev",descricao:"Devoluções de Produtos",nivel:1,valor:dreJulhoFinal.devolucoes,criterio:"Matriz + filial."},
    {id:"icms-m",descricao:"ICMS Matriz",nivel:1,valor:Math.max(0,mov("2827")),criterio:"Somente ICMS das vendas externas; transferências Matriz → Filial ficam patrimoniais."},
    {id:"icms-f",descricao:"ICMS s/ vendas Filial",nivel:1,valor:Math.max(0,mov("25054")),criterio:"Débito da filial líquido dos créditos/estornos que movimentam a mesma conta de resultado."},
    {id:"ipi-m",descricao:"IPI Matriz",nivel:1,valor:Math.max(0,mov("2826")),criterio:"IPI das saídas da matriz conforme apuração oficial."},
    {id:"ipi-f",descricao:"IPI Filial",nivel:1,valor:Math.max(0,mov("25055")),criterio:"IPI da filial líquido do crédito de devolução."},
    {id:"pis",descricao:"PIS",nivel:1,valor:dreJulhoFinal.pis,criterio:"Movimento líquido da conta de PIS sobre vendas após créditos de devolução lançados na própria conta."},
    {id:"cof",descricao:"COFINS",nivel:1,valor:dreJulhoFinal.cofins,criterio:"Movimento líquido da conta de COFINS sobre vendas."},
    {id:"st",descricao:"ICMS ST",nivel:1,valor:dreJulhoFinal.icmsSt,criterio:"Apuração ICMS-ST de julho."},
    {id:"rl",descricao:"(=) Receita Operacional Líquida",nivel:0,valor:dreJulhoFinal.receitaLiquida,criterio:"Receita bruta menos deduções formadas no Razão."},
    {id:"custos",descricao:"(-) Custos / CPV / CMV",nivel:0,valor:dreJulhoFinal.custosReconhecidos,criterio:"Custos resultantes das compras, créditos fiscais e fechamento físico de estoques da matriz e filial.",composicao:grupos.custos},
    {id:"lb",descricao:"(=) LUCRO BRUTO",nivel:0,valor:lucroBruto,criterio:"Receita líquida menos custos contabilizados."},
    {id:"despesas",descricao:"(-) Despesas Operacionais",nivel:0,valor:despOper,criterio:"Despesas operacionais líquidas contabilizadas por documento/centro de custo, incluindo a depreciação calculada do imobilizado.",composicao:grupos.despesas},
    {id:"prod",descricao:"Despesas Produção",nivel:1,valor:soma(grupos.prod),criterio:"Centros produtivos.",composicao:grupos.prod},
    {id:"com",descricao:"Despesas Comerciais",nivel:1,valor:soma(grupos.comerciais),criterio:"Centros comerciais, inclusive filial SP.",composicao:grupos.comerciais},
    {id:"adm",descricao:"Despesas Administrativas",nivel:1,valor:soma(grupos.adm),criterio:"Centros administrativos.",composicao:grupos.adm},
    {id:"outras",descricao:"Outras Despesas Operacionais",nivel:1,valor:soma(grupos.outras),criterio:"Contas de resultado operacionais fora dos grupos anteriores, inclusive depreciação sem centro de custo quando aplicável.",composicao:grupos.outras},
    {id:"ro",descricao:"(=) Resultado Operacional",nivel:0,valor:resultadoOper,criterio:"Lucro bruto menos despesas operacionais contabilizadas."},
    {id:"fin-d",descricao:"(-) Despesas Financeiras",nivel:0,valor:despFin,criterio:"Tarifas/IOF e demais despesas financeiras efetivamente documentadas; JCP não foi copiado de junho.",composicao:grupos.financeira},
    {id:"fin-r",descricao:"(+) Receitas Financeiras",nivel:0,valor:dreJulhoFinal.receitasFinanceiras,criterio:"Rendimentos efetivamente apurados nos extratos Itaú, Bradesco e Greencred."},
    {id:"resultado",descricao:"(=) RESULTADO CONTÁBIL 07/2026",nivel:0,valor:dreJulhoFinal.resultado,criterio:"Resultado calculado exclusivamente pelo Razão final de julho. A depreciação do imobilizado já está contabilizada; permanece pendente apenas a folha/provisões de 07/2026."},
  ];
  const expans=linhas.filter(x=>x.nivel===0||(x.composicao?.length??0)>0).map(x=>x.id);const tudo=expans.every(x=>abertas.has(x));function alternar(id:string){setAbertas(a=>{const n=new Set(a);n.has(id)?n.delete(id):n.add(id);return n})}function alternarTudo(){setAbertas(tudo?new Set():new Set(expans));}
  return <div className="grid gap-5">
    <div className="flex flex-wrap items-start justify-between gap-3 border-b pb-4"><div><h1 className="text-xl font-semibold tracking-tight">DRE calculada - Nitaplast 07/2026</h1><p className="mt-1 text-sm text-muted-foreground">Estrutura de junho aplicada à competência de julho. A DRE nasce do Razão/Balancete e não é usada como fonte dos próprios lançamentos.</p></div><div className="flex gap-2"><Badge className="bg-blue-100 text-blue-800 hover:bg-blue-100">Consolidado Matriz + Filial</Badge><Button variant="outline" size="sm" onClick={alternarTudo}>{tudo?"Recolher toda DRE":"Expandir toda DRE"}</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Resumo label="Receita Operacional Bruta" value={dreJulhoFinal.receitaBruta}/><Resumo label="Deduções da Receita Bruta" value={dreJulhoFinal.deducoes}/><Resumo label="Resultado Contábil" value={dreJulhoFinal.resultado} success={dreJulhoFinal.resultado>=0}/><Resumo label="Partidas no Razão" value={resumoFechamentoJulhoFinal.lancamentos} money={false}/></div>
    <Card className="border-blue-500/30 bg-blue-500/5"><CardContent className="pt-6"><p className="font-medium">Regra única aplicada à DRE inteira</p><p className="mt-1 text-sm text-muted-foreground">Documentos → Lançamentos → Razão → Balancete → DRE. O saldo de 30/06 é referência de cálculo, nunca lançamento de abertura. Matriz e filial permanecem identificadas na origem e consolidadas no relatório.</p></CardContent></Card>
    <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-base">DRE 07/2026 — detalhamento completo</CardTitle><CardDescription>Abra as linhas para conferir o critério e a composição contábil por conta e centro de custo.</CardDescription></div><Badge variant="outline">07/2026 · EM FECHAMENTO</Badge></div></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[1080px] text-sm"><thead><tr className="border-b bg-muted text-left text-xs"><th className="p-2">Linha da DRE</th><th className="p-2 text-right">DRE Calculada 07/2026</th><th className="p-2 text-center">Status</th></tr></thead><tbody>{linhas.map(x=>{const exp=x.nivel===0||(x.composicao?.length??0)>0;const aberta=abertas.has(x.id);const destaque=["rl","lb","ro","resultado"].includes(x.id);return [<tr key={x.id} className={`border-b ${x.nivel===0?"bg-slate-100/70 font-semibold":""} ${destaque?"border-y-2":""}`}><td className="p-2" style={{paddingLeft:8+x.nivel*22}}>{exp?<button className="inline-flex items-center gap-1.5 hover:text-primary" onClick={()=>alternar(x.id)}>{aberta?<ChevronDown className="size-4"/>:<ChevronRight className="size-4"/>}{x.descricao}</button>:<span className="pl-[22px]">{x.descricao}</span>}</td><td className="p-2 text-right font-semibold tabular-nums">{brl.format(x.valor)}</td><td className="p-2 text-center"><span className="inline-flex items-center gap-1 text-emerald-700"><CheckCircle2 className="size-4"/>Calculado</span></td></tr>,exp&&aberta?<tr key={`${x.id}-d`} className="border-b bg-slate-50/70"><td colSpan={3} className="p-4 pl-8"><p className="text-xs text-muted-foreground"><strong className="text-foreground">Critério:</strong> {x.criterio}</p>{x.composicao?.length?<Composicao itens={x.composicao}/>:null}</td></tr>:null]})}</tbody></table></CardContent></Card>
    <Card className="border-amber-400/50 bg-amber-50/40"><CardContent className="pt-5"><div className="flex gap-3"><CircleAlert className="mt-0.5 size-5 text-amber-700"/><div><p className="font-semibold">Pendência de fonte, não de processamento</p><p className="mt-1 text-sm text-muted-foreground">No pacote desta conversa não foi localizada folha/provisões de 07/2026. A depreciação já foi calculada pelo módulo Imobilizado usando somente a recorrência efetivamente contabilizada em junho, limitada ao saldo residual e sem estimar taxa ou vida útil. Bancos, aplicações/rendimentos, impostos a recuperar/recolher, créditos PIS/COFINS, ICMS/IPI, estoques e depreciação já estão contabilizados.</p></div></div></CardContent></Card>
  </div>
}
function Resumo({label,value,money=true,success=false}:{label:string;value:number;money?:boolean;success?:boolean}){return <Card><CardContent className="pt-5"><p className="text-xs font-medium text-muted-foreground">{label}</p><p className={`mt-2 text-xl font-semibold tabular-nums ${success?"text-emerald-700":""}`}>{money?brl.format(value):value.toLocaleString("pt-BR")}</p></CardContent></Card>}
function Composicao({itens}:{itens:Item[]}){return <div className="mt-3 overflow-x-auto rounded-md border bg-background"><table className="w-full min-w-[950px] text-xs"><thead><tr className="border-b bg-muted/50 text-left"><th className="p-2">Conta</th><th className="p-2">Classificação</th><th className="p-2">Descrição</th><th className="p-2">CC</th><th className="p-2 text-right">Débitos</th><th className="p-2 text-right">Créditos</th><th className="p-2 text-right">Impacto</th></tr></thead><tbody>{itens.map(x=><tr key={x.id} className="border-b last:border-0"><td className="p-2 font-mono">{x.conta}</td><td className="p-2 font-mono">{x.classificacao}</td><td className="p-2">{x.descricao}</td><td className="p-2">{x.cc} — {x.centroCusto}</td><td className="p-2 text-right tabular-nums">{brl.format(x.debitos)}</td><td className="p-2 text-right tabular-nums">{brl.format(x.creditos)}</td><td className="p-2 text-right font-semibold tabular-nums">{brl.format(x.valor)}</td></tr>)}</tbody></table></div>}