import { CheckCircle2, FileSpreadsheet } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { fechamentoManualJunho, totalDespesasGerenciaisJunho, type StatusFechamento } from "@/data/nitaplast-fechamento-manual-junho";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export function FechamentoManualJunho() {
  const d = fechamentoManualJunho;
  return <section className="grid gap-4 print:hidden">
    <div className="border-b pb-2"><h2 className="text-lg font-semibold">Composição completa do fechamento manual — 06/2026</h2><p className="text-sm text-muted-foreground">Memória de cálculo, origem e situação de cada bloco recebido.</p></div>
    <Card className="border-blue-500/40 bg-blue-500/5"><CardContent className="flex flex-wrap items-start justify-between gap-3 pt-5 text-sm"><div className="flex gap-3"><FileSpreadsheet className="size-5 shrink-0 text-blue-700"/><div><strong>Arquivo de fechamento carregado como referência.</strong><p className="mt-1 text-muted-foreground">Fonte: {d.fonte}. Valores reconstruídos não geram lançamentos no Razão até serem comprovados por documento, conta contábil e centro de custo.</p></div></div><Badge variant="outline">Não contabilizado</Badge></CardContent></Card>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric titulo="Ativo no fechamento" valor={d.balancete.ativo}/><Metric titulo="Passivo + PL + resultado" valor={d.balancete.passivoPlSemResultado + d.balancete.resultadoAcumulado}/><Metric titulo="Prejuízo de junho" valor={-d.dre.prejuizoJunho}/><Metric titulo="Diferença aritmética" valor={d.balancete.diferenca}/></div>

    <Card><CardHeader><CardTitle className="text-base">Composição da DRE</CardTitle><CardDescription>Cada linha traz o valor, a fonte e o grau de comprovação. Total: prejuízo de {brl.format(d.dre.prejuizoJunho)}.</CardDescription></CardHeader><CardContent><Table headers={["Grupo", "Componente", "Fonte", "Valor", "Situação"]}>{d.composicaoDre.map(([grupo, descricao, valor, fonte, status]) => <tr key={`${grupo}-${descricao}`} className="border-b last:border-0"><Td>{grupo}</Td><Td>{descricao}</Td><Td muted>{fonte}</Td><Td money>{brl.format(valor)}</Td><Td><Status value={status}/></Td></tr>)}</Table></CardContent></Card>

    <Card><CardHeader><CardTitle className="text-base">Despesas operacionais a decompor</CardTitle><CardDescription>As nove categorias somam {brl.format(totalDespesasGerenciaisJunho)}. São agrupamentos da planilha, não contas analíticas definitivas do plano Domínio.</CardDescription></CardHeader><CardContent><Table headers={["Classificação provisória", "Categoria", "Valor", "Tratamento"]}>{d.despesasGerenciais.map(([classificacao, descricao, valor]) => <tr key={classificacao} className="border-b last:border-0"><Td mono>{classificacao}</Td><Td>{descricao}</Td><Td money>{brl.format(valor)}</Td><Td><Badge variant="outline">Abrir por nota, conta e CC</Badge></Td></tr>)}</Table></CardContent></Card>

    <Card className="border-blue-500/40"><CardHeader><CardTitle className="text-base">Fechamento periódico do estoque — mesma lógica de maio</CardTitle><CardDescription>O saldo anterior é baixado para a apuração, o inventário físico é reconhecido linha a linha e o ajuste de R$ 150 mil permanece separado da contagem física.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3 text-sm sm:grid-cols-2 xl:grid-cols-4"><Info titulo="Estoque consolidado em 31/05" valor={d.estoque.saldoMaioConsolidado}/><Info titulo="Inventário físico Matriz" valor={d.estoque.inventarioFisicoMatriz}/><Info titulo="Ajuste contábil da MP" valor={d.estoque.ajusteContabilMateriaPrima}/><Info titulo="Estoque contábil Matriz" valor={d.estoque.estoqueContabilMatriz}/><Info titulo="Inventário físico Filial" valor={d.estoque.inventarioFisicoFilial}/><Info titulo="Físico consolidado" valor={d.estoque.inventarioFisicoConsolidado}/><Info titulo="Contábil consolidado" valor={d.estoque.estoqueContabilConsolidado}/><Info titulo="Compras líquidas em análise" valor={d.estoque.comprasInsumosLiquidas}/></div><Table headers={["Conta", "Linha de estoque", "Saldo 31/05", "Físico 30/06", "Ajuste", "Saldo contábil final"]}>{d.estoqueMatrizPorConta.map(([conta, descricao, anterior, fisico, ajuste, final]) => <tr key={conta} className="border-b last:border-0"><Td mono>{conta}</Td><Td>{descricao}</Td><Td money>{brl.format(anterior)}</Td><Td money>{brl.format(fisico)}</Td><Td money>{brl.format(ajuste)}</Td><Td money>{brl.format(final)}</Td></tr>)}</Table></CardContent></Card>

    <Card><CardHeader><CardTitle className="text-base">Remessas para industrialização — contas compensatórias</CardTitle><CardDescription>Controle fora do estoque patrimonial e sem efeito em fornecedor, CPV ou DRE. O retorno CFOP 1903 agora também baixa o material em poder de terceiros.</CardDescription></CardHeader><CardContent className="grid gap-4"><div className="grid gap-3 text-sm sm:grid-cols-2 xl:grid-cols-5"><Info titulo="Saldo anterior" valor={d.remessasIndustrializacao.saldoAnterior}/><Info titulo="Remessas CFOP 5901" valor={d.remessasIndustrializacao.remessasCfop5901}/><Info titulo="Retornos CFOP 1902" valor={-d.remessasIndustrializacao.retornosCfop1902}/><Info titulo="Retornos CFOP 1903" valor={-d.remessasIndustrializacao.retornosCfop1903}/><Info titulo="Saldo final em terceiros" valor={d.remessasIndustrializacao.saldoFinal}/></div><p className="text-xs text-muted-foreground">Espelho contábil: conta devedora {d.remessasIndustrializacao.contaDevedora} e conta credora {d.remessasIndustrializacao.contaCredora}, sempre pelo mesmo valor.</p></CardContent></Card>

    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle className="text-base">Apurações tributárias — Matriz</CardTitle><CardDescription>Valores conferidos nos registros fiscais de junho.</CardDescription></CardHeader><CardContent><Table headers={["Tributo", "Débitos", "Créditos", "A recolher"]}>{d.tributos.map(([nome, debitos, creditos, recolher]) => <tr key={nome} className="border-b last:border-0"><Td>{nome}</Td><Td money>{brl.format(debitos)}</Td><Td money>{brl.format(creditos)}</Td><Td money>{brl.format(recolher)}</Td></tr>)}</Table></CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">Folha por unidade</CardTitle><CardDescription>Composição recebida da folha por centro de custo.</CardDescription></CardHeader><CardContent><Table headers={["Unidade", "Funcionários", "INSS patronal", "Total"]}>{d.folha.map(([unidade, funcionarios, inss]) => <tr key={unidade} className="border-b last:border-0"><Td>{unidade}</Td><Td money>{brl.format(funcionarios)}</Td><Td money>{brl.format(inss)}</Td><Td money>{brl.format(funcionarios + inss)}</Td></tr>)}</Table></CardContent></Card>
    </div>

    <Card><CardHeader><CardTitle className="text-base">Conciliação bancária</CardTitle><CardDescription>Saldos conforme extratos; Greencred e Bradesco 895 ainda têm diferença de implantação.</CardDescription></CardHeader><CardContent><Table headers={["Banco / conta", "Saldo anterior", "Entradas", "Saídas", "Saldo final", "Situação"]}>{d.bancos.map(([banco, conta, anterior, entradas, saidas, final, status]) => <tr key={`${banco}-${conta}`} className="border-b last:border-0"><Td>{banco}<span className="block text-xs text-muted-foreground">{conta}</span></Td><Td money>{brl.format(anterior)}</Td><Td money>{brl.format(entradas)}</Td><Td money>{brl.format(saidas)}</Td><Td money>{brl.format(final)}</Td><Td><Status value={status}/></Td></tr>)}</Table></CardContent></Card>

    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle className="text-base">Cobertura dos arquivos</CardTitle><CardDescription>O que está disponível e o que ainda falta abrir no ERP.</CardDescription></CardHeader><CardContent className="grid gap-2">{d.cobertura.map(([item, detalhe, status]) => <div key={item} className="flex items-start justify-between gap-3 rounded-md border p-3"><div><p className="text-sm font-medium">{item}</p><p className="text-xs text-muted-foreground">{detalhe}</p></div><Status value={status}/></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">Pendências de fechamento</CardTitle><CardDescription>Pontos que impedem tratar a planilha como contabilização definitiva.</CardDescription></CardHeader><CardContent className="grid gap-2">{d.pontosRevisao.map(([item, impacto, status, observacao]) => <div key={item} className="rounded-md border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{item}</p><p className="text-xs text-muted-foreground">Impacto: {impacto}</p></div><Status value={status}/></div><p className="mt-2 text-xs text-muted-foreground">{observacao}</p></div>)}</CardContent></Card>
    </div>

    <Card className="border-emerald-500/40 bg-emerald-500/5"><CardContent className="flex gap-3 pt-5 text-sm"><CheckCircle2 className="size-5 shrink-0 text-emerald-700"/><div><strong>A planilha fecha aritmeticamente em R$ 0,00.</strong><p className="mt-1 text-muted-foreground">Isso confirma a soma interna, mas não substitui as conciliações de estoque, CPV, bancos, filial, LALUR e a abertura das despesas.</p></div></CardContent></Card>
  </section>;
}

function Status({ value }: { value: StatusFechamento }) { const variant = value === "Verificado" ? "default" : value === "Pendente" || value === "Não verificado" ? "destructive" : "outline"; return <Badge variant={variant}>{value}</Badge>; }
function Metric({ titulo, valor }: { titulo: string; valor: number }) { return <Card><CardContent className="pt-5"><p className="text-xs text-muted-foreground">{titulo}</p><p className="mt-1 text-lg font-semibold tabular-nums">{brl.format(valor)}</p></CardContent></Card>; }
function Info({ titulo, valor }: { titulo: string; valor: number }) { return <div><p className="text-xs text-muted-foreground">{titulo}</p><p className="mt-1 font-semibold tabular-nums">{brl.format(valor)}</p></div>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground">{headers.map((h, i) => <th key={h} className={`p-2 ${i > 2 ? "text-right" : ""}`}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Td({ children, money, muted, mono }: { children: React.ReactNode; money?: boolean; muted?: boolean; mono?: boolean }) { return <td className={`p-2 align-top ${money ? "text-right font-medium tabular-nums" : ""} ${muted ? "text-xs text-muted-foreground" : ""} ${mono ? "font-mono" : ""}`}>{children}</td>; }
