import { AlertTriangle, Boxes, CheckCircle2, FileCheck2, Landmark, Scale } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { calculoJcpJulho, estoqueFinalMatrizJulhoPorConta, estoqueFinalMatrizJulhoTotal, fiscalJulho, receitaFiscalJulho } from "@/data/nitaplast-fechamento-julho";
import { dreJulhoFinal } from "@/data/nitaplast-dre-julho-final";
import { resumoFechamentoJulhoFinal } from "@/data/nitaplast-razao-julho-final";
import { resumoIntegracaoBancariaJulho } from "@/data/nitaplast-bancos-julho-completo";
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
function Metric({label,value,detalhe}:{label:string;value:number;detalhe?:string}){return <div className="rounded-lg border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums">{brl.format(value)}</p>{detalhe?<p className="mt-1 text-[11px] text-muted-foreground">{detalhe}</p>:null}</div>}
export function FechamentoNitaplastJulho(){return <div className="grid gap-4">
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Receita bruta contabilizada" value={dreJulhoFinal.receitaBruta} detalhe="Matriz + filial, somente vendas externas."/><Metric label="Resultado contábil calculado" value={dreJulhoFinal.resultado} detalhe="Já inclui a depreciação do imobilizado; permanece pendente a folha/provisões."/><Metric label="Inventário matriz 31/07" value={estoqueFinalMatrizJulhoTotal} detalhe="Fechamento físico já levado ao Razão/CPV."/><Metric label="Depreciação 07/2026" value={resumoFechamentoJulhoFinal.depreciacaoJulho} detalhe="Calculada pelo módulo Imobilizado, sem estimar taxa ou vida útil."/></div>
  <Card className="border-emerald-500/40 bg-emerald-50/40"><CardContent className="pt-6"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 size-5 text-emerald-700"/><div><p className="font-semibold">Escrituração contábil de julho formada</p><p className="mt-1 text-sm text-muted-foreground">A competência 07/2026 já contém lançamentos de documentos fiscais, bancos, aplicações, impostos, créditos tributários, compras, matriz/filial, fechamento de estoques e depreciação do imobilizado. O mesmo Razão alimenta Balancete, Diário e DRE. Débitos {brl.format(resumoFechamentoJulhoFinal.debitos)} = Créditos {brl.format(resumoFechamentoJulhoFinal.creditos)}.</p></div></div></CardContent></Card>
  <div className="grid gap-4 xl:grid-cols-2">
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Landmark className="size-4"/> Bancos e aplicações</CardTitle><CardDescription>Extratos recebidos e conciliados na escrituração.</CardDescription></CardHeader><CardContent className="grid gap-2 text-sm"><Linha n="Fontes bancárias recebidas" v={`${resumoIntegracaoBancariaJulho.fontesRecebidas}`}/><Linha n="Greencred — posição bruta" v={brl.format(resumoIntegracaoBancariaJulho.posicoes.greencredBruto)}/><Linha n="Bradesco Maxi DI — posição bruta" v={brl.format(resumoIntegracaoBancariaJulho.posicoes.bradescoMaxiBruto)}/><Linha n="Bradesco CDB — posição bruta" v={brl.format(resumoIntegracaoBancariaJulho.posicoes.bradescoCdbBruto)}/><Linha n="Itaú aplicação automática — posição bruta" v={brl.format(resumoIntegracaoBancariaJulho.posicoes.itauAutoBruto)}/><Linha n="Itaú Trust DI — posição final" v={brl.format(resumoIntegracaoBancariaJulho.posicoes.itauTrustBruto)}/><Linha n="Bradesco 895 Invest Fácil — posição bruta" v={brl.format(resumoIntegracaoBancariaJulho.posicoes.bradesco895InvestBruto)}/></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Scale className="size-4"/> Impostos apurados</CardTitle><CardDescription>Débitos, créditos e saldos de julho já refletidos no Razão.</CardDescription></CardHeader><CardContent className="grid gap-2 text-sm"><Linha n="ICMS matriz a recolher" v={brl.format(resumoFechamentoJulhoFinal.icmsMatrizRecolher)}/><Linha n="ICMS filial — crédito a transportar" v={brl.format(resumoFechamentoJulhoFinal.icmsFilialCredito)}/><Linha n="IPI matriz a recolher" v={brl.format(resumoFechamentoJulhoFinal.ipiMatrizRecolher)}/><Linha n="IPI filial a recolher" v={brl.format(resumoFechamentoJulhoFinal.ipiFilialRecolher)}/><Linha n="Créditos PIS apropriados" v={brl.format(resumoFechamentoJulhoFinal.pisCreditos)}/><Linha n="Créditos COFINS apropriados" v={brl.format(resumoFechamentoJulhoFinal.cofinsCreditos)}/><Linha n="PIS débito sobre saídas" v={brl.format(fiscalJulho.contribuicoes.pisDebitoSaidas)}/><Linha n="COFINS débito sobre saídas" v={brl.format(fiscalJulho.contribuicoes.cofinsDebitoSaidas)}/></CardContent></Card>
  </div>
  <div className="grid gap-4 xl:grid-cols-2">
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Boxes className="size-4"/> Estoque matriz — fechamento 31/07</CardTitle><CardDescription>Os saldos físicos oficiais já são os saldos finais patrimoniais.</CardDescription></CardHeader><CardContent className="grid gap-2 text-sm">{Object.entries(estoqueFinalMatrizJulhoPorConta).map(([c,v])=><Linha key={c} n={`Conta ${c}`} v={brl.format(v)}/>) }<Linha n="Total matriz" v={brl.format(estoqueFinalMatrizJulhoTotal)} strong/></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FileCheck2 className="size-4"/> Receita e DRE</CardTitle><CardDescription>Resultado calculado a partir do Razão final.</CardDescription></CardHeader><CardContent className="grid gap-2 text-sm"><Linha n="Produção — matriz" v={brl.format(receitaFiscalJulho.matriz.producao)}/><Linha n="Revenda — matriz" v={brl.format(receitaFiscalJulho.matriz.revenda)}/><Linha n="Produção/operação triangular — filial" v={brl.format(receitaFiscalJulho.filialSp.producaoOperacaoTriangular)}/><Linha n="Revenda — filial" v={brl.format(receitaFiscalJulho.filialSp.revenda)}/><Linha n="Depreciação do imobilizado" v={brl.format(resumoFechamentoJulhoFinal.depreciacaoJulho)}/><Linha n="Receita líquida calculada" v={brl.format(dreJulhoFinal.receitaLiquida)} strong/><Linha n="Resultado contábil calculado" v={brl.format(dreJulhoFinal.resultado)} strong/></CardContent></Card>
  </div>
  <Card className="border-blue-400/50 bg-blue-50/40"><CardHeader><div className="flex flex-wrap items-start justify-between gap-2"><div><CardTitle className="flex items-center gap-2 text-base"><Landmark className="size-4"/> JCP — cálculo de julho/2026</CardTitle><CardDescription>Cálculo disponível para decisão societária. Ainda não é lançamento contábil.</CardDescription></div><Badge variant="outline">Não lançado no Razão</Badge></div></CardHeader><CardContent className="grid gap-2 text-sm"><Linha n="Base de cálculo considerada" v={brl.format(calculoJcpJulho.base.total)}/><Linha n="TJLP de julho" v={`${calculoJcpJulho.tjlp.taxaMensalPercentual.toLocaleString("pt-BR",{minimumFractionDigits:4,maximumFractionDigits:4})}%`}/><Linha n="JCP calculado" v={brl.format(calculoJcpJulho.jcpCalculado)} strong/><Linha n="IRRF reconhecido agora" v={brl.format(calculoJcpJulho.irrfReconhecidoAgora)}/><Linha n="IRRF potencial se houver crédito ao sócio" v={brl.format(calculoJcpJulho.irrfPotencialSeCreditado)}/><p className="pt-2 text-xs text-muted-foreground">A conta contábil de reserva de capital aparece em {brl.format(calculoJcpJulho.base.reservaCapitalContabil)}, mas foi mantida fora da base até validação da natureza societária. O cálculo não altera junho e não alimenta Razão, Balancete ou DRE enquanto não houver deliberação/crédito individualizado.</p></CardContent></Card>
  <Card className="border-amber-400/50 bg-amber-50/40"><CardContent className="pt-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 size-5 text-amber-700"/><div><p className="font-semibold">Fonte ainda não localizada no pacote de julho</p><p className="mt-1 text-sm text-muted-foreground"><strong>Folha/provisões de férias e 13º de 07/2026</strong>. Os relatórios de folha localizados no pacote são de 06/2026, então não foram copiados para julho. A depreciação já está calculada e contabilizada pelo módulo Imobilizado usando a recorrência efetivamente registrada em junho, limitada ao saldo residual. O JCP de julho está calculado, mas permanece fora do Razão aguardando deliberação/crédito; a variação cambial continua fora por decisão operacional. As pequenas contrapartidas que a própria base não identifica permanecem como revisão visível, sem lançamento de encaixe.</p><div className="mt-3 flex flex-wrap gap-2"><Badge variant="outline">{resumoFechamentoJulhoFinal.lancamentos} partidas</Badge><Badge variant="outline">{resumoFechamentoJulhoFinal.movimentosBancariosFonte} movimentos bancários fonte</Badge><Badge variant="outline">{brl.format(resumoFechamentoJulhoFinal.pendenciasBancariasValor)} em revisão bancária</Badge></div></div></div></CardContent></Card>
</div>}
function Linha({n,v,strong=false}:{n:string;v:string;strong?:boolean}){return <div className={`flex justify-between gap-3 border-b py-2 last:border-0 ${strong?"font-semibold":""}`}><span>{n}</span><span className="tabular-nums">{v}</span></div>}
